config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :positions
  resources :trainings
  resource :homes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :trainings, :through => :training_positions
  has_many :training_positions

  validates :title, presence: true,uniqueness: true
end

app/models/training.rb
class Training < ApplicationRecord
  has_many :positions, :through => :training_positions
  has_many :training_positions

  validates :name,presence: true, uniqueness: true
  validates :number_of_day, numericality: { message: 'should be a number' }, allow_blank: true
end

app/models/training_position.rb
class TrainingPosition < ApplicationRecord
  belongs_to :position
  belongs_to :training
  validates :training_id, uniqueness: {scope: :position_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @positions = Position.all
    @trainings = Training.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @positions = Position.all
    @trainings = Training.all
    # @selections = TrainingPosition.all
  end

  def create
    trainings_params.each do |data|
      data.to_h.each_pair do |content, index|
        Training.find_by_name(content).position_ids = index.reject(&:blank?)
      end
    end
    redirect_to root_path
  end

  private

  def trainings_params
    params.slice(:trainings).permit![:trainings]
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController

  def index
   @positions = Position.all
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      redirect_to positions_path
    else
      @errors = @position.errors.full_messages
    end
  end

  def edit
    @position = Position.find(params[:id])
  end

  def update
    @position = Position.find(params[:id])
    if @position.update_attributes(position_params)
      redirect_to positions_path
    else
      @errors = @position.errors.full_messages
    end
  end

  def destroy
    @position = Position.find(params[:id])
    if @position.destroy
      redirect_to positions_path
    end
  end

  private

  def position_params
    params.require(:position).permit(:title, :description)
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def index
    @trainings = Training.all
  end

  def new
    @training = Training.new
  end

  def create
    @training = Training.new(training_params)
    if @training.save
      redirect_to trainings_path
    else
      @errors = @training.errors.full_messages
    end
  end

  def edit
    @training = Training.find(params[:id])
  end

  def update
    @training = Training.find(params[:id])
    if @training.update_attributes(training_params)
      redirect_to trainings_path
    else
      @errors = @training.errors.full_messages
    end
  end

  def destroy
    @training = Training.find(params[:id])
    if @training.destroy
      redirect_to trainings_path
    end
  end

  private

  def training_params
    params.require(:training).permit(:name,:certification,:number_of_day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/homes/index.html.erb
<div class="col-lg-12">
  <h3>Matrix Table</h3>
  <% if (@positions && @trainings).present? %>
      <div class="col-lg-10">
        <p class="position-text"><b>Positions</b></p>
        <%= form_tag homes_path do |f|%>
            <table class="responsive-table-input-matrix">
              <thead>
              <tr>
                <td></td>
                <% @positions.each do |position|%>
                    <td><%=position.title%></td>
                <% end %>
              </tr>
              </thead>
              <tbody>
              <% @trainings.each do |training|%>
                  <tr>
                    <td><%= training.name %></td>
                    <% @positions.each do |position|%>
                        <%= hidden_field_tag "trainings[]#{training.name}[]",nil , id: dom_id(training) %>
                        <td><%= check_box_tag "trainings[]#{training.name}[]", position.id,training.position_ids.include?(position.id),id: dom_id(position) %></td>
                    <% end %>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <br/>
            <%= submit_tag "Submit", class: "btn btn-primary" %>
        <% end %><br>
        <p class="training-text"><b>Trainings</b></p>
      </div>
  <% else %>
      <p>No Record is Found</p>
  <% end %>
  <div class="col-lg-2">
    <%= link_to "Create Position", positions_path,:class => "pull-right btn btn-info" %><br><br>
    <%= link_to "Create Training", trainings_path,:class => "pull-right btn btn-warning" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matrix</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
  </head>

  <body>
    <div class="container" style="background-color:#F5F5F5">
      <%= render 'shared/header' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/positions/_form.html.erb
<div class="form-div">
  <%= form_for @position,remote: true  do |f| %>
      <div id='position_title'>
        <ul></ul>
      </div>
      <div class="form-group">
        <%= f.text_field :title,:class => "form-control",:placeholder=>"Title"%>
      </div>
      <div class="form-group">
        <%= f.text_area :description, :rows => 2, :cols => 60 , :maxlength => 50, :minlength=> 5, :class => "form-control",:placeholder=>"Description" %>
      </div>
      <div class="form-group">
        <%if params[:action] == 'edit'%>
            <%= f.submit "Update Position",:class => "btn btn-primary pull-left"%>
        <% else %>
            <%= f.submit "Create Position",:class => "btn btn-primary pull-left"%>
        <% end %>
      </div></br></br>
  <% end %>
  <%= link_to "Back",positions_path ,:class=>"btn btn-success"%>
</div>

app/views/positions/create.js.erb
<% if @errors.present? %>
<% @errors.each do |error| %>
var error = "<%= error%>";
$('#position_title ul').html('<li class="error">'+error+'</li>');
<% end %>
<% else %>
$("#position_title")[0].reset();
$("#position_description")[0].reset();
<% end %>

app/views/positions/edit.html.erb
<%= render "form" %>

app/views/positions/index.html.erb
<div class="form-div">
  <%= link_to "CreatePosition", new_position_path,:class => "btn btn-primary pull-left" %><br><br><br>
  <table class="table table-striped">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="2">Action</th>
    </tr>
    <% @positions.each do |position| %>
        <tr>
          <td><%= position.title %></td>
          <td><%= position.description %></td>
          <td><%= link_to 'Edit', edit_position_path(position) %></td>
          <td><%= link_to 'Destroy',position_path(position) ,:method => :delete , :data=> { :confirm=> 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </table>
  <%= link_to "Back",root_url,:class=>"btn btn-success" %>
</div>

app/views/positions/new.html.erb
<%= render "form" %>

app/views/positions/update.js.erb
<% if @errors.present? %>
<% @errors.each do |error| %>
var error = "<%= error%>";
$('#position_title ul').html('<li class="error">'+error+'</li>');
<% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="col-lg-12">
  <div class="footer">
    <ul class="list-inline footer-list">
      <li><a href="/" class="footer-link">Home</a></li>|
      <li>Privacy Policy</li>|
      <li>Copyright (c) 2016 matrix</li>
    </ul>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="col-lg-12">
  <div class="header">
    <%= link_to "MATRIX", root_path ,:class=>"heading-title"%>
    <ul class="nav nav-pills pull-right menu-list">
      <li><%= link_to "HOME",root_path,:class=> "menu-item-text" %></li>
    </ul>
  </div>
</div>

app/views/trainings/_form.html.erb
<div class="form-div">
  <%= form_for @training,remote: true  do |f| %>
      <div id='training_name'>
        <ul></ul>
      </div>
      <div class="form-group">
        <%= f.text_field :name,:class => "form-control",:placeholder=>"Name"%>
      </div>
      <div class="form-group">
        <%= f.text_field :certification,:class => "form-control",:placeholder=>"Add the type of Certificate you want?"%>
      </div>
      <div class="form-group">
        <%= f.text_field :number_of_day,:class => "form-control",:placeholder=>"Duration in Days"%>
      </div>
      <div class="form-group">
        <%if params[:action] == 'edit'%>
            <%= f.submit "Update Training",:class => "btn btn-primary pull-left"%>
        <% else %>
            <%= f.submit "Create Training",:class => "btn btn-primary pull-left"%>
        <% end %>
      </div><br><br>
  <% end %>
  <%= link_to "Back",trainings_path ,:class=>"btn btn-success"%>
</div>

app/views/trainings/create.js.erb
<% if @errors.present? %>
<% @errors.each do |error| %>
var error = "<%= error%>";
$('#training_name ul').html('<li class="error">'+error+'</li>');
<% end %>
<% end %>

app/views/trainings/edit.html.erb
<%= render "form" %>

app/views/trainings/index.html.erb
<div class="form-div">
  <%= link_to "CreateTraining", new_training_path,:class => "btn btn-primary pull-left"%><br><br><br>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Certification</th>
      <th>Number of Days</th>
      <th colspan="2">Action</th>
    </tr>
    <% @trainings.each do |training| %>
        <tr>
          <td><%= training.name %></td>
          <td><%= training.certification %></td>
          <td><%= training.number_of_day %></td>
          <td><%= link_to 'Edit', edit_training_path(training) %></td>
          <td><%= link_to 'Destroy',training_path(training) ,:method => :delete ,remote: true, :data=> { :confirm=> 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </table>
  <%= link_to "Back",root_url,:class=>"btn btn-success" %>
</div>

app/views/trainings/new.html.erb
<%= render "form" %>

app/views/trainings/update.js.erb
<% if @errors.present? %>
  <% @errors.each do |error| %>
    var error = "<%= error%>";
    $('#training_name ul').html('<li class="error">'+error+'</li>');
  <% end %>
<% end %>